### ISSUE TITLE
demo nb was reverted back to old version with recent commit, need to push latest version

### ISSUE THREAD

**Issue by LindsayRAbrams** [oceanhackweek/ohw20-proj-glide-data-fetcher#19]

**Comment by ocefpaf** [comment]
I think that this point in the git history has what we need: https://github.com/oceanhackweek/ohw20-proj-glide-data-fetcher/blob/faf62e601de64ed823f844207c1726f6d6a78379/notebooks/demo.ipynb

**Comment by ocefpaf** [comment]
Actually, scratch that, it seems that latest master does have the plotting stuff correctly.

**Comment by LindsayRAbrams** [comment]
Yep @callumrollo and I realized it was correct. It just didn't match my master once I closed the branch I used to make the changes. Closing this issue.
