### ISSUE TITLE
Add some plotting functionality

### ISSUE THREAD

**Issue by ocefpaf** [oceanhackweek/ohw20-proj-glide-data-fetcher#7]
We should add some quick exploration plots, like a track map and a property section. The former is relatively easy, the latter will take some consideration on what defines a section.

**Comment by LindsayRAbrams** [comment]
@ocefpaf I can work on creating a function for plotting in the demo notebook. Is this the best place for it for now? And by property  section do you mean the transect for a variable, i.e., temperature? Like you did in your DataAccess notebook?

**Comment by LindsayRAbrams** [comment]
Went ahead and added a couple of plotting functions for track map and transect following Filipe's examples from his DataAccess nb. Still confused how to connect my pull request to the appropriate issue.

**Comment by ocefpaf** [comment]
Yep. That is what I had in mind. To "connect" you can mention it in the title or the text of the PR. Something like: closed by #8
